# DoE | Planejando Experimentos com Python

Nesta atividade, vamos gerar diferentes planos experimentais.

Para tal, utilizaremos a biblioteca `pyDOE2` ([informações](https://pypi.org/project/pyDOE2/) e [documentação](https://pythonhosted.org/pyDOE/)).

O Colab não vem com essa biblioteca pré-instalada, então Vamos começar instalando essa biblioteca usando o `pip`.

### Antes de começar: Instale o `pyDOE2` usando o pip.
Dica: No Colab, temos que colocar um sinal de `!` antes do `pip`, assim: `!pip`

In [1]:
# instalando pyDOE2
!pip install pyDOE2

  Preparing metadata (setup.py) ... done
  Created wheel for pyDOE2: filename=pyDOE2-1.3.0-py3-none-any.whl size=25521 sha256=be984acf30cc5176500317db687854d6b570dd078ce78b1faedbcacd61024b36
  Stored in directory: /root/.cache/pip/wheels/46/1f/29/6fda5c72f950841e39147ae603780ee913a62f977b4ad47ee4
Successfully built pyDOE2


Após instalar a biblioteca, importe-a e importe também as suas dependências `numpy`e `scipy`:

In [2]:
# Importações necessárias
import pandas as pd
import numpy as np
import scipy as sp
import pyDOE2 as doe

# Geração de Matrizes de Projeto

O pyDOE2 permite criar matrizes de projeto que definem as configurações dos fatores experimentais a serem testados. A  biblioteca suporta vários tipos de matrizes, incluindo:

* **Fatoriais completos**: gera uma matriz de todos os possíveis níveis de todos os fatores.
* **Fatoriais fracionados**: gera uma matriz de uma fração dos níveis possíveis para todos os fatores, reduzindo o número total de configurações a serem testadas.

Vamos praticar ao longo das atividades a seguir:

## Atividade 1: Fatorial Completo de 3 Fatores e 2 Níveis

Nesta abordagem pode haver **apenas dois níveis** por fator.
Esses valores serão representados pelos valores `1` e `-1`.

Dica: Para Fatorial Completo de 2 Níveis, utilizaremos a função `ff2n`.

In [3]:
# Fatorial Completo
# 3 Fatores com 2 Níveis
design1 = doe.ff2n(3)

print(len(design1))
design1

8


array([[-1., -1., -1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1.,  1.]])

**PERGUNTA:** Quantas configurações serão testadas no experimento?

>   **RESPOSTA:** 8 Configurações

## Atividade 2: Fatorial Completo (mais de 2 níveis)
Nesta abordagem, pode haver **mais que apenas 2 níveis por fator**, permitindo maior flexibilidade. No entanto, isso irá aumentar a complexidade do experimento.

Crie um Design Fatorial Completo com 3 fatores, com a seguinte configuração:
* O primeiro fator tem 3 níveis;
* O segundo fator tem 2 níveis;
* O terceiro fator tem 4 níveis;

Dica: para Fatorial Completo Geral, utilizaremos a função `fullfact`.



In [4]:
# 3 Fatores com Níveis diferentes
plan = [3,2,4]

design2 = doe.fullfact(plan)

print(len(design2))
design2

24


array([[0., 0., 0.],
       [1., 0., 0.],
       [2., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [2., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [2., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [0., 0., 2.],
       [1., 0., 2.],
       [2., 0., 2.],
       [0., 1., 2.],
       [1., 1., 2.],
       [2., 1., 2.],
       [0., 0., 3.],
       [1., 0., 3.],
       [2., 0., 3.],
       [0., 1., 3.],
       [1., 1., 3.],
       [2., 1., 3.]])

**PERGUNTA:** Quantas configurações serão testadas no experimento?

  > **RESPOSTA:** 24 Configurações

## Atividade 3: Fatorial Completo de 3 Fatores e 2 Níveis (parte 2)

Suponha que para a produção de um bolo pronto, desejemos testar os seguintes fatores e níveis:

**Fator 1 | Farinha:**
Tipo 1 ou Tipo 2

**Fator 2 | Quantidade de Fermento:**
24mg ou 36mg

**Fator 3 | Temperatura:**
140ºC ou 180ºC

**INSTRUÇÕES:**

**A.** Gere o plano experimental de fatorial completo utilizando o pyDOE2

**B.** A partir do resultado, crie um DataFrame com o plano expermental, substituindo os valores *1* e *-1* pelos valores reais a serem testados.

In [5]:
# Fatorial Completo
design3 = doe.ff2n(3)

print(len(design3))
design3

8


array([[-1., -1., -1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [6]:
# Copiando o Fatorial Completo
D1 = design3.copy()

# Fator 1
D1[:,0][D1[:,0] == 1] = 1
D1[:,0][D1[:,0] == -1] = 2

# Fator 2
D1[:,1][D1[:,1] == 1] = 24
D1[:,1][D1[:,1] == -1] = 36

# Fator 3
D1[:,2][D1[:,2] == 1] = 140
D1[:,2][D1[:,2] == -1] = 180

In [7]:
# Nomeando Colunas
c_names = ['Farinha', 'Quantidade de Fermento', 'Temperatura']
# Criando DataFrame
df1 = pd.DataFrame(D1, columns=c_names)
# Exibir Resultado
display(df1)

Farinha  Quantidade de Fermento  Temperatura
0      2.0                    36.0        180.0
1      1.0                    36.0        180.0
2      2.0                    24.0        180.0
3      1.0                    24.0        180.0
4      2.0                    36.0        140.0
5      1.0                    36.0        140.0
6      2.0                    24.0        140.0
7      1.0                    24.0        140.0

## Atividade 4: Fatorial Fracionado de 3 Fatores e 2 Níveis

Suponha que antes de rodar um experimento mais complexo como o proposto anteriormente, você decida fazer uma rodada preliminar e mais simples. Assim, você decidirá se os Fatores escolhidos (Tipo da Farinha, Quantidade de Fermento e Temperatura do Forno) aparentam ter de fato algum efeito significativo sobre o sabor do bolo.

Para tal, você decidiu optar por um desenho experimental com apenas 4 experimentos, em vez dos 8 experimentos anteriores.

### Atividade 4.1: Gere um desenho Fatorial Fracionado de 3 Fatores e 2 Níveis

In [8]:
# Fatorial Fracionado
gen = 'A B AB'

design4 = doe.fracfact(gen)

print(len(design4))
design4

4


array([[-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.]])

### Atividade 4.2: Crie um DataFrame com os valores das variáveis a serem testadas no experimento anterior

In [9]:
# Copiando o Fatorial Fracionado
D2 = design4.copy()

# Fator 1
D2[:,0][D2[:,0] == 1] = 1
D2[:,0][D2[:,0] == -1] = 2

# Fator 2
D2[:,1][D2[:,1] == 1] = 24
D2[:,1][D2[:,1] == -1] = 36

# Fator 3
D2[:,2][D2[:,2] == 1] = 140
D2[:,2][D2[:,2] == -1] = 180

In [10]:
# Nomeando Colunas
c_names = ['Farinha', 'Quantidade de Fermento', 'Temperatura']
# Criando DataFrame
df2 = pd.DataFrame(D2, columns=c_names)
# Exibir Resultado
display(df2)

Farinha  Quantidade de Fermento  Temperatura
0      2.0                    36.0        140.0
1      1.0                    36.0        180.0
2      2.0                    24.0        180.0
3      1.0                    24.0        140.0

### Atividade 4.3: Invertendo as combinações do Fatorial Fracionado

Suponha que uma colega de equipe com mais experiência em produtos dessa categoria pede que no plano experimental seja contemplada uma combinação específica, não prevista inicialmente. A combinação é a seguinte:

**Farinha:** Tipo 2

**Quantidade de Fermento:** 36mg

**Temperatura:** 180ºC

Adapte o plano experimental de forma que o número de combinações (unidades experimentais) se mantenha o mesmo (4), mas que seja possível testar a combinação proposta.

Dica: Consulte a documentação do pyDOE2 neste [link](https://pythonhosted.org/pyDOE/factorial.html)

In [11]:
# Fatorial Fracionado
gen = 'A B -AB'

design5 = doe.fracfact(gen)

print(len(design5))
design5

4


array([[-1., -1., -1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1., -1.]])

In [12]:
# Copiando o Fatorial Fracionado
D3 = design5.copy()

# Fator 1
D3[:,0][D3[:,0] == 1] = 1
D3[:,0][D3[:,0] == -1] = 2

# Fator 2
D3[:,1][D3[:,1] == 1] = 24
D3[:,1][D3[:,1] == -1] = 36

# Fator 3
D3[:,2][D3[:,2] == 1] = 140
D3[:,2][D3[:,2] == -1] = 180

In [13]:
# Nomeando Colunas
c_names = ['Farinha', 'Quantidade de Fermento', 'Temperatura']
# Criando DataFrame
df3 = pd.DataFrame(D3, columns=c_names)
# Exibir Resultado
display(df3)

Farinha  Quantidade de Fermento  Temperatura
0      2.0                    36.0        180.0
1      1.0                    36.0        140.0
2      2.0                    24.0        140.0
3      1.0                    24.0        180.0

## Atividade 5

Suponha que a rodada experimental inicial teve resultados bastante proveitosos e foi possível concluir que as Farinhas dos tipos 1 e 2 (ambas super premium) são praticamente iguais. Assim, optar-se-á pela Farinha do tipo 1, que tem um valor mais baixo.

Também percebeu-se que a temperatura de 140ºC foi insuficiente em todos os casos. Assim, decidiu-se testar as temperaturas de 160ºC e de 180ºC.

De modo geral, a rodada inicial correu bem e rapidamente. Por isso, a equipe resolveu incluir outros fatores que não haviam sido testados anteriormente.

Na segunda rodada, serão testados os seguintes fatores:

**A) Quantidade de Fermento:**
24mg ou 36mg

**B) Temperatura:**
160ºC ou 180ºC

**C) Tempo:**
35min ou 40min

**D) Ovos:**
3 ou 4

### Atividade 5.1: Faça uma estimativa de quantos testes seriam necessários para testar todas as possibilidades

In [14]:
# Fatorial Completo
design6 = doe.ff2n(4)

print(len(design6))
design6

16


array([[-1., -1., -1., -1.],
       [ 1., -1., -1., -1.],
       [-1.,  1., -1., -1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1., -1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1.,  1., -1.],
       [ 1.,  1.,  1., -1.],
       [-1., -1., -1.,  1.],
       [ 1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1.,  1.,  1.],
       [-1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

> **RESPOSTA:** 16 Configurações

### Atividade 5.2: Crie um desenho fatorial fracionado
Crie um plano experimental para os fatores listados acima de forma que sejam testadas apenas 8 receitas:

**A) Quantidade de Fermento:**
24mg ou 36mg

**B) Temperatura:**
160ºC ou 180ºC

**C) Tempo:**
35min ou 40min

**D) Ovos:**
3 ou 4

In [15]:
# Fatorial Fracionado
gen = 'A B C ABC'

design7 = doe.fracfact(gen)

print(len(design7))
design7

8


array([[-1., -1., -1., -1.],
       [ 1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1.,  1., -1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
# Copiando o Fatorial Fracionado
D4 = design7.copy()

# Fator 1
D4[:,0][D4[:,0] == 1] = 24
D4[:,0][D4[:,0] == -1] = 36

# Fator 2
D4[:,1][D4[:,1] == 1] = 160
D4[:,1][D4[:,1] == -1] = 180

# Fator 3
D4[:,2][D4[:,2] == 1] = 35
D4[:,2][D4[:,2] == -1] = 40

# Fator 4
D4[:,3][D4[:,3] == 1] = 3
D4[:,3][D4[:,3] == -1] = 4

In [17]:
# Nomeando Colunas
c_names = ['Quantidade de Fermento', 'Temperatura', 'Tempo', 'Ovos']
# Criando DataFrame
df4 = pd.DataFrame(D4, columns=c_names)
# Exibir Resultado
df4

Quantidade de Fermento  Temperatura  Tempo  Ovos
0                    36.0        180.0   40.0   4.0
1                    24.0        180.0   40.0   3.0
2                    36.0        160.0   40.0   3.0
3                    24.0        160.0   40.0   4.0
4                    36.0        180.0   35.0   3.0
5                    24.0        180.0   35.0   4.0
6                    36.0        160.0   35.0   4.0
7                    24.0        160.0   35.0   3.0

### Extra: Teste outras configurações, compare os dataframes gerados

Há várias maneiras de gerar os desenhos experimentais.
Sugestão: compare os dataframes utilizando a função `concat` do pandas.

# Testando outra configuração

In [18]:
# Fatorial Fracionado
gen = 'A B C -ABC'

design8 = doe.fracfact(gen)

print(len(design8))
design8

8


array([[-1., -1., -1.,  1.],
       [ 1., -1., -1., -1.],
       [-1.,  1., -1., -1.],
       [ 1.,  1., -1.,  1.],
       [-1., -1.,  1., -1.],
       [ 1., -1.,  1.,  1.],
       [-1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., -1.]])

In [19]:
# Copiando o Fatorial Fracionado
D5 = design8.copy()

# Fator 1
D5[:,0][D5[:,0] == 1] = 24
D5[:,0][D5[:,0] == -1] = 36

# Fator 2
D5[:,1][D5[:,1] == 1] = 160
D5[:,1][D5[:,1] == -1] = 180

# Fator 3
D5[:,2][D5[:,2] == 1] = 35
D5[:,2][D5[:,2] == -1] = 40

# Fator 4
D5[:,3][D5[:,3] == 1] = 3
D5[:,3][D5[:,3] == -1] = 4

In [20]:
# Exibir Resultado
c_names = ['Quantidade de Fermento', 'Temperatura', 'Tempo', 'Ovos']
# Criando DataFrame
df5 = pd.DataFrame(D5, columns=c_names)
# Exibir Resultado
df5

Quantidade de Fermento  Temperatura  Tempo  Ovos
0                    36.0        180.0   40.0   3.0
1                    24.0        180.0   40.0   4.0
2                    36.0        160.0   40.0   4.0
3                    24.0        160.0   40.0   3.0
4                    36.0        180.0   35.0   4.0
5                    24.0        180.0   35.0   3.0
6                    36.0        160.0   35.0   3.0
7                    24.0        160.0   35.0   4.0

# Comparando os Resultados

In [21]:
# Concatenado o df1 com o df2 para visualizar o todo
comparacao0 = pd.concat([df1,df2], axis=0)
comparacao0

Farinha  Quantidade de Fermento  Temperatura
0      2.0                    36.0        180.0
1      1.0                    36.0        180.0
2      2.0                    24.0        180.0
3      1.0                    24.0        180.0
4      2.0                    36.0        140.0
5      1.0                    36.0        140.0
6      2.0                    24.0        140.0
7      1.0                    24.0        140.0
0      2.0                    36.0        140.0
1      1.0                    36.0        180.0
2      2.0                    24.0        180.0
3      1.0                    24.0        140.0

In [22]:
# Concatenado o df1 com o df3 para visualizar o todo
comparacao1 = pd.concat([df1,df3], axis=0)
comparacao1

Farinha  Quantidade de Fermento  Temperatura
0      2.0                    36.0        180.0
1      1.0                    36.0        180.0
2      2.0                    24.0        180.0
3      1.0                    24.0        180.0
4      2.0                    36.0        140.0
5      1.0                    36.0        140.0
6      2.0                    24.0        140.0
7      1.0                    24.0        140.0
0      2.0                    36.0        180.0
1      1.0                    36.0        140.0
2      2.0                    24.0        140.0
3      1.0                    24.0        180.0

In [23]:
# Concatenado o df2 com o df3 para visualizar o todo
comparacao2 = pd.concat([df2,df3], axis=0)
comparacao2

Farinha  Quantidade de Fermento  Temperatura
0      2.0                    36.0        140.0
1      1.0                    36.0        180.0
2      2.0                    24.0        180.0
3      1.0                    24.0        140.0
0      2.0                    36.0        180.0
1      1.0                    36.0        140.0
2      2.0                    24.0        140.0
3      1.0                    24.0        180.0

In [24]:
# Concatenado o df4 com o df5 para visualizar o todo
comparacao3 = pd.concat([df4,df5], axis=0)
comparacao3

Quantidade de Fermento  Temperatura  Tempo  Ovos
0                    36.0        180.0   40.0   4.0
1                    24.0        180.0   40.0   3.0
2                    36.0        160.0   40.0   3.0
3                    24.0        160.0   40.0   4.0
4                    36.0        180.0   35.0   3.0
5                    24.0        180.0   35.0   4.0
6                    36.0        160.0   35.0   4.0
7                    24.0        160.0   35.0   3.0
0                    36.0        180.0   40.0   3.0
1                    24.0        180.0   40.0   4.0
2                    36.0        160.0   40.0   4.0
3                    24.0        160.0   40.0   3.0
4                    36.0        180.0   35.0   4.0
5                    24.0        180.0   35.0   3.0
6                    36.0        160.0   35.0   3.0
7                    24.0        160.0   35.0   4.0